### ISSUE TITLE
个人中心--作业界面

### ISSUE THREAD

**Issue by gang-GitHub** [BillZhangHL/EduBugManagement#63]
**手机端** 

*问题描述：*作业界面太简陋，需要李栋设计
![92602638522059738](https://user-images.githubusercontent.com/6790972/33156253-dfdc40b2-d032-11e7-921f-33f294af9eb6.jpg)

**Comment by BillZhangHL** [comment]
这就是李栋设计的，还有，在李栋没有github账号前，有这种要设计的想法直接跟李栋沟通，不要添加到bug列表中。
